// Fixed allowlist of icon names shared with the public website's icon-name
// resolver. These are `icon` string values only — never uploaded images.
// Must stay in sync with the lucide-react component names.
export const ICON_NAMES = [
  'Trophy',
  'CalendarCheck',
  'UserCheck',
  'BadgeCheck',
  'Paintbrush',
  'Home',
  'Sparkles',
  'Building2',
  'Zap',
  'Wrench',
  'Droplets',
  'PanelsTopLeft',
  'Landmark',
  'Hammer',
  'HardHat',
  'Gem',
  'WalletCards',
  'TimerReset',
  'WandSparkles',
  'ShieldCheck',
  'Brush',
  'Handshake',
  'PaintBucket',
  'Star',
  'Clock3',
  'PhoneCall',
  'MapPin',
  'Mail',
  'MessageCircle',
  'Phone',
  'CheckCircle2',
  'ChevronDown',
  'Quote',
  'CalendarDays',
  'Camera',
  'CirclePlay',
  'Share2',
  'Award',
  'ThumbsUp',
  'Layers',
];
